### ISSUE TITLE
Configured name.d.ts in a different location than sprive.svg

### ISSUE THREAD

**Issue by nirtamir2** [alexanderson1993/svg-icons-cli#5]
Hi!
Thank you for creating this library!
I love it!
I want to have a file structure where like
<img width="180" alt="image" src="https://github.com/alexanderson1993/svg-icons-cli/assets/16452789/7e3407c1-9c2c-4d63-bbae-caa2452f242e">
and put the `sprite.svg` in `public/icons/sprite.svg` (because it has to be in public directory). 
I would like that it will happen in the script command. 
Maybe having something like `--sprite-path="public/icons/sprite.svg"` would be nice
Thanks!

**Comment by alexanderson1993** [comment]
I like that, and I can see how it would be necessary in some frameworks.

I can't get around to this right away, so feel free to submit a PR. Otherwise, I'll try to add this feature within a week.

**Comment by alexanderson1993** [comment]
I've realized that you'd likely run into caching issues if you put the sprite file into your `/public` folder, since most frameworks put aggressive, long-lived caches on `/public` files, assuming they don't change often. Files that do change are given content hashes in the filenames.

But if we give `sprite.svg` a content hash if we put it in the public folder, you'd have to update that URL in your code as well. It gets messy.

I'm inclined to change this to `wont-fix` since it could result in a worse DX and UX. What framework are you using? I'd love to help find a way to make this work with your framework, so the framework can add content hashes to the filenames instead of working against your framework.

**Comment by nirtamir2** [comment]
I'm using Next.js
The script I'm using is `icons build -i ./src/assets/icons -o src/components/ui/icons`
What do you suggest?
How to use the Icon component in your opinion with Next.js? I want to be able to override `currentColor` from outside component

**Comment by alexanderson1993** [comment]
I understand. The problem is that if you deploy your app, and then users visit your app, the `sprite.svg` file will be cached for them with a long expiration time. So if you add new icons and then re-deploy, those users won't see the new icons unless they clear their cache. 

There are two possible solutions:
- Make it so the sprite.svg file is given a content hash filename. This requires also updating the URL where `sprite.svg` is accessed in your Icon component.
- Let your framework handle adding the content hash for you, as part of its automated build step. This is what Vite (and, by extension, Remix) does. I think you need something like this to make it work with Next.js https://github.com/twopluszero/next-images

**Comment by nirtamir2** [comment]
> I understand. The problem is that if you deploy your app, and then users visit your app, the sprite.svg file will be cached for them with a long expiration time. So if you add new icons and then re-deploy, those users won't see the new icons unless they clear their cache.

https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets#caching


> [Caching](https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets#caching)
Next.js cannot safely cache assets in the public folder because they may change. The default caching headers applied are:


```
Cache-Control: public, max-age=0
```

---

Are you sure?

**Comment by alexanderson1993** [comment]
Interesting, and noted. Okay, we can add this. It just needs to include a disclaimer explaining the tradeoffs you're making for non-Next.js frameworks that do cache `/public`.

**Comment by nirtamir2** [comment]
I can do breaking things, or just do this. 

```diff
Subject: [PATCH] revert diff
sprite location
fix icon-name.d.ts instead of name.d.ts
---
Index: README.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/README.md b/README.md
--- a/README.md	(revision 42356ba4e7ab03175526374d163a8c51d834334c)
+++ b/README.md	(revision 070b622523436a04ce3ee5d3021150b82d0e9b6f)
@@ -57,6 +57,7 @@
 #### Options
 
 - `-o, --output`: Where to store the Icon component. Defaults to `components/ui`
+- `--spriteDir`: Where to store the sprite svg. Defaults to output arg value
 - `-t, --types`: Where to store the default type definition file. Defaults to `types/icon-name.d.ts`
 
 > [!NOTE] > **Why not export `<Icon>` from this package?**
Index: index.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/index.js b/index.js
--- a/index.js	(revision 42356ba4e7ab03175526374d163a8c51d834334c)
+++ b/index.js	(revision 070b622523436a04ce3ee5d3021150b82d0e9b6f)
@@ -68,6 +68,7 @@
   Options:
     -i, --input     The relative path where the source SVGs are stored
     -o, --output    Where the output sprite sheet and types should be stored
+    --spriteDir     Where the output sprite sheet should be stored (default to output param)
     --optimize      Optimize the output SVG using SVGO. 
     --help          Show help
   `,
@@ -143,6 +144,7 @@
   }
   if (isCancel(output)) process.exit(1);
   const outputDir = path.join(cwd, output);
+  const spriteDir = path.join(cwd, args.spriteDir ?? output);
   if (typeof args.optimize === "undefined") {
     const choseOptimize = await confirm({
       message: "Optimize the output SVG using SVGO?",
@@ -169,7 +171,7 @@
     process.exit(1);
   } else {
     mkdirSync(outputDir, { recursive: true });
-    const spriteFilepath = path.join(outputDir, "sprite.svg");
+    const spriteFilepath = path.join(spriteDir, "sprite.svg");
     const typeOutputFilepath = path.join(outputDir, "name.d.ts");
     const currentSprite = await fs
       .readFile(spriteFilepath, "utf8")

```

**Comment by nirtamir2** [comment]
For those who want to just get it to work in next.js - you can use the `mv` command
```
icons build -i ./src/assets/icons -o src/components/ui/icons && mv ./src/components/ui/icons/sprite.svg ./public/icons
```
@alexanderson1993 If you want - I created a PR #7
